### ISSUE TITLE
Improvement: prettify app

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/covid19_bed_occupancy#13]
Would include:

* adding separators between the graphs
* add a couple of `br()` after the last graph
* whatever else is relevant in terms of styling, colors etc. :)

**Comment by thibautjombart** [comment]
@samclifford tagged you here shamelessly but please feel free to decline if no time today

**Comment by samclifford** [comment]
Working on this now.

**Comment by samclifford** [comment]
Pull request #20

**Comment by samclifford** [comment]
I'm not totally smitten with the colour scheme used for the quantiles and would probably prefer a ribbon xor lines. I've tried defining a colour palette using the colours [here](https://ble.lshtm.ac.uk/pluginfile.php/56085/mod_resource/content/3/LSHTM%20brand%20guidelines%202017.pdf)

**Comment by thibautjombart** [comment]
I like the new version. Currently the plot for the distribution and the one for prediction have the same 'importance'; I am thinking it would make sense to prioritise projections. We could:

* move the LoS distributions beneath?
* move the LoS distributions to a separate tab?
* make hte LoS distributions smaller?
* only show them if a box 'show LoS distro' is ticked?

What do you think?

**Comment by samclifford** [comment]
I think moving them underneath for context without them being the major result is fine

**Comment by thibautjombart** [comment]
Cool. Would you be able to do it? No worries if not.

**Comment by samclifford** [comment]
On it right now.
