### ISSUE TITLE
Improve handling of uncertainty

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/covid19_bed_occupancy#16]
From @erees 's review on a [PR](https://github.com/thibautjombart/covid19_bed_occupancy/pull/11):

> ![Screenshot 2020-03-26 at 09 03 22](https://user-images.githubusercontent.com/22442251/77629346-45090d80-6f41-11ea-8d81-70f683cbabb7.png)
> 
> Just testing out the app on my computer. Seems to be running fine. One thing - when you put a lower doubling time (1.5) and keep the uncertainty in doubling times at default (1) the credible intervals become so wide the graph is no longer usefull (added screen shot to show what I mean). I think Sam may have mentioned a solution to it? It's just from reading a doubling time of ~2 has been reported for many countries so it's likely many people will try these and may be worth doing something before first release. Sorry if this is already being worked on and I've missed it

Alternatives that have been discussed:

* change input: doubling time -> growth rate, and display the corresponding doubling time in the GUI
* @samclifford had ideas for a better approach

**Comment by pearsonca** [comment]
n.b., #19 also includes changing this to the % version suggested on the call.

**Comment by esnightingale** [comment]
I had assigned this to myself but will unassign since Carl has addressed it

**Comment by thibautjombart** [comment]
Thanks, done now.
