### ISSUE TITLE
Review code of functions implementing the model

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/covid19_bed_occupancy#17]
The following 3 files in `app/R/` implement the model (the rest is merely auxiliary functions):

- [x] `predict_admissions.R`: predict daily incidence of admissions 
- [x] `predict_beds.R` : uses the input of the above and info on duration of hospitalisation to predict bed requirements 
- [x] `run_model.R`: wraps around the first 2

**Comment by thibautjombart** [comment]
@noamross if you wanted to get an idea of how the model works you could have a look at these files, these are the main functions implementing bed predictions. Should be good to go once [this PR](https://github.com/thibautjombart/covid19_bed_occupancy/pull/11) is through (within minutes).

**Comment by esnightingale** [comment]
Have looked through and don't have anything to add.

**Comment by thibautjombart** [comment]
@esnightingale Great thanks.

**Comment by esnightingale** [comment]
The amendment for % doubling error isn't quite right - since you're dividing by 1+/-error the low and high come out the wrong way around. Just need to swap the +/- I think?

**Comment by thibautjombart** [comment]
Sorry there's been lots of changes over the last hours. Current release candidate is now on `master`

**Comment by samclifford** [comment]
Can this be closed now?
