### ISSUE TITLE
App authors in acknowledgements

### ISSUE THREAD

**Issue by samclifford** [thibautjombart/covid19_bed_occupancy#22]
The app authors aren't a subset of the paper authors and I think it warrants more than just membership of the COVID-19 Working Group in the Info tab. Suggest either acknowledgement in the app title, footer, or acknowledgements.

**Comment by thibautjombart** [comment]
I agree!

**Comment by thibautjombart** [comment]
Could be a separate tab too.

**Comment by samclifford** [comment]
Making a new tab for acknowledgements
