### ISSUE TITLE
Move code for plotting distro to R/

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/covid19_bed_occupancy#26]
This:
https://github.com/thibautjombart/covid19_bed_occupancy/blob/master/app/app.R#L102-L118

Should be put in `R/` , ideally with brief roxygen documentation. Note that `cmmid_color` shound not be the default in the function definition as it is not defined then.

**Comment by thibautjombart** [comment]
@samclifford assigning you coz of your past work on graphs for the app, but feel free to de-assign yourself.

**Comment by samclifford** [comment]
@pearsonca wrote this one and I'm happy to handle it but I'm not using it as of 7e03960a734d8f7dc63552027ea7153a40416f11

**Comment by thibautjombart** [comment]
Ah okay cool! Removing it from the code then .
