### ISSUE TITLE
Hospital and ICU beds GUIs are 'independent' and could be made clearer

### ISSUE THREAD

**Issue by kath-o-reilly** [thibautjombart/covid19_bed_occupancy#35]
Really great app and very useful I'm sure. From a users perspective I'd recommend making it clearer that each page / ICU vs hospitalisation are independent. So, if a user wants to specify certain parameters and see the result they need to input these parameters twice (unless I am mistaken?). To make it clearer, either state this somewhere, or on the 'overall' page include the parameters to the right of each figure. Or, there might be merit in having the option to run sims for both outputs at the same time.

**Comment by thibautjombart** [comment]
There are 2 aspects to this: a design choice, and the underlying model. These are now discussed in the following issues:

* design: https://github.com/thibautjombart/covid19_bed_occupancy/issues/42
* model: https://github.com/thibautjombart/covid19_bed_occupancy/issues/40

**Comment by thibautjombart** [comment]
Closing this one - conversations will continue on the other threads.
