### ISSUE TITLE
Zero uncertainty

### ISSUE THREAD

**Issue by mert0248** [thibautjombart/covid19_bed_occupancy#38]
Roz noted that sometimes the projection has zero uncertainty.
![image](https://user-images.githubusercontent.com/48446255/77834770-f7f28a80-713e-11ea-87dd-af038330bc96.png)

**Comment by thibautjombart** [comment]
This shot is not very informative. I can reproduce something similar:
![image](https://user-images.githubusercontent.com/10757154/77849496-eb644580-71c3-11ea-833e-c701b0fab5f4.png)

This are tiny numbers and very early on. Also note that we allow for uncertainty in growth = 0, so the only remaining uncertainty comes from LoS. This kind of result is not surprising.
