### ISSUE TITLE
Interplay between general ward and ICU bed LOS

### ISSUE THREAD

**Issue by mert0248** [thibautjombart/covid19_bed_occupancy#40]
We have separate inputs for admissions to general ward beds and for ICU beds. However many ICU patients will be admitted from and discharge to a general ward bed. The hospital length of stay distribution from Zhou et al. almost certainly includes the time that a sub-set of patients spent in ICU. Our general bed occupancy projections could therefore overestimate general ward bed occupancy.

**Comment by thibautjombart** [comment]
Important to discuss with everyone @erees @samclifford @pearsonca @esnightingale . 
So far we don't have data on hospitalisation trajectories, but I think @gwenknight might look into this. For now I will add this as a caveat in the information tab.

For the interpretation of the results of Zhou et al @mert0248 I am not sure it is that certain, as they provide the 2 distributions side by side. Admission to a different ward should count as discharge from the previous ward.

**Comment by thibautjombart** [comment]
Clarification and caveats added at cd2bd58dcffef21afc17697cdce7fd879dead294

**Comment by johnurbanik** [comment]
Hey all, great work thus far.

I spent a little bit of time looking at the Zhou et. al. results. Based on the results from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1097734/, the best estimate for mean is sample median, so we can make some rough assumptions of additivity here. The same cannot be said for variance, so I'll focus on the medians not the quartiles here.

|                                                       | Total (n=191)   | Non-survivor(n=54)  | Survivor (n=137)  | p value   |
|-----------------------------------------------------  |---------------  |-------------------- |------------------ |---------  |
| Time from illness onset to hospital admission, days   | 11 (8-14)       | 11 (8-15)           | 11 (8-13)         | .53       |
| ICU Admission                                         | 50 (26%)        | 39 (72%)            | 11 (8%)           | <1E-4     |
| ICU Length of Stay                                    | 8 (4-12)        | 8 (4-12)            | 7 (2-9)           | 0.41      |
| Hospital Length of Stay                               | 11 (7-14)       | 7.5 (5-11)          | 12 (9-15)         | <1E-4     |
| Time from illness onset to ICU admission, days        | 12 (8-15)       | 12 (8-15)           | 11.5 (8-14)       | .88       |
| Time from illness onset to death or discharge         | 21 (17-25)      | 18.5(15-22)         | 22 (18-25)        | 3E-4      |

Let's denote `Time from illness onset to hospital admission` as  D, `ICU length of stay` as I, `Hospital length of stay` as H,  `Time from illness onset to ICU admission days` as Q, and `Time from illness onset to death or discharge` as L.

Based on this distribution, it seems likely that in non survivors, Dn+Hn ~= Ln, so H is the total duration of hospitalization, including ICU stay in a subset. However, the data also suggests that a large fraction of patients were admitted directly to the ICU, given Q ~= D. 15 patients (28%) who died were never submitted to the ICU. 

Under this interpretation, it seems likely that only a small fraction of patients started in the general ward (for any large amount of time) and then transitioned to the ICU. However, survivors initially admitted to the ICU likely transition back to the general ward for at least a few days before discharge, which could be an important effect to model, especially under overflow conditions.

Under this formulation, your tool should have 1 input for admissions (with a single distribution), and a fraction of these admissions would go to the ICU (stochastically), after some period of time (time from illness onset to ICU admission, in the paper). At ICU admission, a fraction of patients would die and a fraction would return to the general pool for the remainder of time. There are some more mixtures in there (general->ICU->general, general->ICU), but this would at least bring things closer to matching the data in Zhou et. al.

I will be making a separate issue about the validity of the duration distributions, as I think that there are some serious issues with the experimental design in this study. I'd love to discuss with you all as opposed to just whistleblowing, as there might be something I'm missing here.

**Comment by esnightingale** [comment]
Some info on CC-specific LOS here, but stratified by survival/death: https://www.icnarc.org/About/Latest-News/2020/03/27/Report-On-775-Patients-Critically-Ill-With-Covid-19

**Comment by thibautjombart** [comment]
Nice! tagging @mert0248 for awareness; should add this to https://github.com/thibautjombart/covid19_bed_occupancy/issues/49
