### ISSUE TITLE
Moving back to single tab

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/covid19_bed_occupancy#42]
Several comments on the app e.g. https://github.com/thibautjombart/covid19_bed_occupancy/issues/35 suggested forecasts for the 2 types of hospitalisation could be on the same page. This is down to personnal preferences to a large extent, but leaving space for a discussion here.

## Pro 2 tabs

* clearer outputs
* ability to model both separately
* ability to put both results on the same page if needed

## Pro 1 tab

* common growth parameters and numbers of simulations make sense

**Comment by samclifford** [comment]
I suggest making the doubling time common to both ICU and non-ICU beds by reusing the same input box. Otherwise when you flick to the Overall tab and have two different doubling times you get inconsistent results.

**Comment by thibautjombart** [comment]
I agree. It seems we agree on reverting back to a single tab. @pearsonca agreed to take the lead on this. Renaming issue accordingly.

**Comment by thibautjombart** [comment]
Closed via 0e32999bab666d44945e5febbac9b5a0a0b54363
