### ISSUE TITLE
los link to each type of bed

### ISSUE THREAD

**Issue by gwenknight** [thibautjombart/covid19_bed_occupancy#44]
It seems like there isn't really two los options - instead just one is for non-critical and one for critical care now? 
Was it deemed to complicated to allow users to change this distribution themselves? can imagine that this might be useful

**Comment by thibautjombart** [comment]
The original version was like this, but the group decided to go with 2 tabs later on. There are ongoing discussions on this choice:
https://github.com/thibautjombart/covid19_bed_occupancy/issues/42
