### ISSUE TITLE
Add beds from past admissions

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/covid19_bed_occupancy#46]
Currently, the model only predicts bed occupancy using admissions from the date of reference. This means beds currently occupied, from past admissions, are not being used, leading to under-estimating bed occupancy in the first days of the simulations.

A better approach would be to append forecasted admissions to past admission data, and the derive the bed occupancy predictions.

**Comment by pearsonca** [comment]
So the input here is...for the beds currently occupied, when were they admitted? Then there's some sort of conditional forecast of when they'll leave, which we augment going forward.

Ideally the input would be line-list-ish with admit date, discharge date (which might be empty) - then could estimate real length of stay distro (and growth rate, etc).

**Comment by thibautjombart** [comment]
That would be the ideal scenario - estimate LoS, maybe a Poisson model for
admissions over time etc. Not ruling out that we include this in the
future, but at least as a first fix we should allow for admissions over the
last few days to be provided. Under-estimates can be big in packed
hospitals over the first few days, especially if growth rate is low. Would
be particularly problematic in decreasing phases of epidemics, as we are
likely to see repeatedly after lockdowns.

// sent from my Armor5 phone

**Comment by esnightingale** [comment]
Would these already-admitted cases be subject to the same LOS distn from their original date of admission? Would there need to be a recommended minimum number of previous days' data, related to assumed LOS, so that we can reasonably assume ongoing occupancies have been captured?

**Comment by gwenknight** [comment]
Are you talking about COVID patients or non-COVID patients? I think COVID wards are now being segregated. So we could talk about bed occupancy just in these areas, then we don't have to worry about non-COVID occupancy. If you are talking about COVID patients then can't we ask for an incidence and use the same method to go forward from their first start date?

**Comment by thibautjombart** [comment]
> Would these already-admitted cases be subject to the same LOS distn from their original date of admission? Would there need to be a recommended minimum number of previous days' data, related to assumed LOS, so that we can reasonably assume ongoing occupancies have been captured?

Yes exactly the same as admissions we forecast, and only COVID patients. Again, the app is *only* for COVID patients.

**Comment by thibautjombart** [comment]
> Are you talking about COVID patients or non-COVID patients? I think COVID wards are now being segregated. So we could talk about bed occupancy just in these areas, then we don't have to worry about non-COVID occupancy. If you are talking about COVID patients then can't we ask for an incidence and use the same method to go forward from their first start date?

Only COVID, and yes, that's the idea. Only we don't want to impose the entire time series (we discussed this during the call this morning). We'll clarify that when a single date is provided, we only model occupancy from new admissions. As an option, users will be able to upload a xslx / csv to provide incidence of admissions over several days.

**Comment by esnightingale** [comment]
would it be possible to model this as something survival-y or is that too complicated?

**Comment by thibautjombart** [comment]
Not a bad idea, but not for the next release ;)

**Comment by thibautjombart** [comment]
Data inputs moved to a dedicated issue: https://github.com/thibautjombart/covid19_bed_occupancy/issues/51

Forecast / model changes moved to a dedicated issue: https://github.com/thibautjombart/covid19_bed_occupancy/issues/52

**Comment by thibautjombart** [comment]
Done at ad1c0560d98c0131f23cd2858178d12b45a1f4cf
