### ISSUE TITLE
Interactions between hospitalized demographic and length of stay

### ISSUE THREAD

**Issue by johnurbanik** [thibautjombart/covid19_bed_occupancy#48]
I'm not sure how this would be modeled given the datasets we have available now, but there are likely interactions between demographic information and length of stay that would change expected occupancy pretty substantially.

For example, in places like Sweden where elderly people are far more insulated from the virus than somewhere like Italy, it may be the case that the average length of stay is substantially shorter (or perhaps that ICU stay is longer, as the rate of comorbidities is lower so severe cases may be less immunocompromised?).

These demographic extremes are actually quite likely given that the virus spreads heterogeneously: the hospitalized demographics will be quite different per population. We've seen this manifest when comparing age distributions in Lombardy to Germany to NY. Perhaps it would be possible to use the current hospitalization demographics as an initial condition, and at least include priors over CFR to sort people into the ICU / general ward buckets? 

Beyond that, we likely need a new dataset to understand the distributional mixture of length of hospital stay with demographic info as covariates... hopefully someone researchers are working on that somewhere.

**Comment by thibautjombart** [comment]
I agree. I think in the short term the least we can do is allow users to
specify their own distribution for LoS.

Will create a new issue tomorrow (well, several actually) and set up a call
with the team. ETA for new release: by the end of the weekend.

// sent from my Armor5 phone

**Comment by thibautjombart** [comment]
To elaborate on previous reply:

- specifying e.g. age-specific LoS and separately the age distribution: possible in theory, harder in practice; app would become more complicated and most users will not have these data

- this said, LoS from the location considered may well be able to the user, and would encapsulate the above as long as there are no drastic demographic shifts in infections (probable safe assumption); this would be solved by allowing users to specify params of the LoS, relating to https://github.com/thibautjombart/covid19_bed_occupancy/issues/9

**Comment by thibautjombart** [comment]
Closing to follow on https://github.com/thibautjombart/covid19_bed_occupancy/issues/49 and https://github.com/thibautjombart/covid19_bed_occupancy/issues/9
