### ISSUE TITLE
Add input for past admission data

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/covid19_bed_occupancy#51]
We should provide a template and facilities for inputing data on past admissions. This would have to be optional, so the default behaviour remains the current inputs.

### Items

* [x] box tick input to uncover the file upload input, below the current data inputs
* [x] reactive UI to show template download / file upload if the box above is ticked
* [x] a template file, with 2 columns (`date` in format *yyyy-mm-dd* and `n_admissions`) 
* [x] a button for downloading template file (`.xlsx`)
* [x] a button for uploading data
* [x] an internal function in `R/` to check / process uploaded data (with meaningfull errors where relevant)
 

### Notes

There are ways to edit tables from shiny directly e.g.:
https://blog.rstudio.com/2018/03/29/dt-0-4/

But I think uploading xlsx is safer

**Comment by thibautjombart** [comment]
@samclifford tagging you here but feel free to un-assign; probably best done after the 1 tab reform (https://github.com/thibautjombart/covid19_bed_occupancy/issues/42)

**Comment by samclifford** [comment]
I love the idea of a downloadable template. Suggest we also include a data dictionary as the second sheet if it's going to be an XLSX format.

For the error checking I'm thinking it might be worth running a date cleaner from https://github.com/reconhub/linelist rather than being sticklers for the date format. So long as it's  unambiguous that's the main thing.

**Comment by thibautjombart** [comment]
> I love the idea of a downloadable template. Suggest we also include a data dictionary as the second sheet if it's going to be an XLSX format.
> 
> For the error checking I'm thinking it might be worth running a date cleaner from https://github.com/reconhub/linelist rather than being sticklers for the date format. So long as it's unambiguous that's the main thing.

Yep, and yep, totally agreed :)

**Comment by thibautjombart** [comment]
Done as of ad1c0560d98c0131f23cd2858178d12b45a1f4cf
