### ISSUE TITLE
Renaming data and parameter input tabs

### ISSUE THREAD

**Issue by samclifford** [thibautjombart/covid19_bed_occupancy#60]
It's not immediately clear what the links are between the Data and parameter inputs tabs and the mainPanel results tabs.

Suggest the following renaming

| old | new |
| --- | --- |
| Data | Case dates |
| Duration of hospitalisation | Length of stay in hospital | 
| Growth parameters | Epidemic growth parameters | 
| Simulation parameters | Duration and number of simulations | 

| old | new |
| --- | --- |
| Length of hospitalisation | Plot: Length of stay in hospital |
| Doubling time distribution | Plot: Epidemic doubling time |
| Main results | Results: Projected bed occupancy |

And projected bed occupancy should probably be first in the results tabs.

**Comment by thibautjombart** [comment]
Done for all at 49050bc95c1682abfb2f85885e7777a647b77086 except for "main results" which I thought was more intuitive.
