### ISSUE TITLE
Reporting rate

### ISSUE THREAD

**Issue by gwenknight** [thibautjombart/covid19_bed_occupancy#61]
This is now only for people if they upload their own admission data? I wonder if it should be removed all together. Or at least from the description on the inputs or moved to above the slider that appears ("Reporting rate refers to the % of COVID-19 admissions reported as such.").

**Comment by gwenknight** [comment]
Adding to this: in the model description it says "Augment the number of admissions by an assumed level of reporting. This is currently done by:
naug = nreported / %reported " but this _doesn't_ (?) happen if they enter just a number of people / day in admissions?

**Comment by gwenknight** [comment]
Following through - on the input tab it says default to 100% for reporting rate but there is no option to change if just do admissions on single day?

**Comment by thibautjombart** [comment]
It should do. Reporting should be handled the same way irrespective of the type of data input. Will check and fix.

**Comment by thibautjombart** [comment]
It was indeed a bug, thanks for catching it! 
Fixed at 982fdeb0573035d05b31b3d427827507fc9b6576
