### ISSUE TITLE
Add in "gamma" distribution to LoS?

### ISSUE THREAD

**Issue by gwenknight** [thibautjombart/covid19_bed_occupancy#63]
should we say "gamma" on the inputs?

**Comment by thibautjombart** [comment]
Just to clarify: do you mean on the left panel or in the tab explaining what the inputs are?

**Comment by gwenknight** [comment]
on the left panel

**Comment by thibautjombart** [comment]
I have added "See inputs for details on these distributions" in the legend on the left panel. This is because each choice is potentially a different distribution, and we want to increase this choice in future releases. 

Closed via 9fb9b9c858889897ba99d033562faca2122069ad
