### ISSUE TITLE
Input - caveats

### ISSUE THREAD

**Issue by gwenknight** [thibautjombart/covid19_bed_occupancy#65]
Remove at least the first sentence of this?
"The bed occupancy in non-critical and critial wards are modelled independently, so that there is no interplay between the two. Fruther refinements of the model are looking at incorporating patient movements between non-critical and critical care wards."

**Comment by thibautjombart** [comment]
You're right, I think actually both should be removed, and we can always point out to your work when it's released. Marking as fix before release as this is quick and should have been removed.

**Comment by thibautjombart** [comment]
https://github.com/thibautjombart/covid19_bed_occupancy/pull/70
