### ISSUE TITLE
No accounting for past trends in prediction? 

### ISSUE THREAD

**Issue by gwenknight** [thibautjombart/covid19_bed_occupancy#66]
Am I right in thinking that the model just appends an exponential curve on the end of any admission data? e.g. if I input a plateau then it starts increasing again? I think perhaps worth stating this as a caveat? 
- User inputted data only contributes to bed requirements and any trend in user data does not impact on the assumed exponential growth from the final time point of data inputted. 
Or something eloquent!

**Comment by samclifford** [comment]
It also considers the discharge of those who have previously been admitted, no?

**Comment by thibautjombart** [comment]
Gwen is right about the forecasting of admissions; discharge: implicitly yes, as we account for past admissions + LoS

**Comment by thibautjombart** [comment]
closed at d1d78228cd2e8e6ed83dbfb452bc2e326fffba79
