### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by esnightingale** [thibautjombart/covid19_bed_occupancy#69]
If you upload a random xlsx file and try to generate results, you get the error "Error: undefined columns selected" which looks like the default R error. Could we change it to something more informative e.g. "Error: Uploaded data are named incorrectly. Please check template for the required structure."

**Comment by samclifford** [comment]
This should just be a simple check that there are only two named columns as expected, that they're of the correct types, contain valid dates in a valid range, and that none of the case values are negative.

**Comment by thibautjombart** [comment]
@samclifford can you handle this one?

**Comment by thibautjombart** [comment]
Removing the documentation label as really it should be code changes (adding more checks to input).

Also, not providing any file for input currently generates an error on the result panel. We need to e.g. return `NULL` by default and adapt the plotting.

**Comment by esnightingale** [comment]
> @samclifford can you handle this one?

Yes I just started having a go and think will be too slow :P

**Comment by thibautjombart** [comment]
OK no worries

**Comment by thibautjombart** [comment]
Should be fixed at 81f6f20801617149bf313429855fe403b72bbe86

@esnightingale can you check that there is now a meaningful error?

**Comment by esnightingale** [comment]
When I add negative admissions I get "invalid 'times' argument" - what does that mean?

**Comment by thibautjombart** [comment]
Should be fixed at 0a46b1085ea76de46d5e0d1ecd9c10c2ad25c78b
Can you try again?

**Comment by thibautjombart** [comment]
Sorry, on branch `prerelease`

**Comment by esnightingale** [comment]
Yep works great
