### ISSUE TITLE
GUI: add ability to specify range of values for doubling time (and others?)

### ISSUE THREAD

**Issue by samclifford** [thibautjombart/covid19_bed_occupancy#7]
For each parameter that we want to consider being drawn from a distribution, it would be good to have a drop-down menu for log-Normal, Gamma and Uniform. If a log-Normal or Gamma are selected, users should be asked to provide two quantiles. A uniform distribution should ask for a min and max. It should be clear to the users which parameters are being asked for.

Other options include specifying the mean and variance of a Gamma distribution and doing moment matching to determine the shape and rate/scale parameters. Asking for the mean and variance of a log-Normal is a bad idea because the mapping from log-N(x) to N of log(x) is not straightforward.

**Comment by thibautjombart** [comment]
@samclifford feel free to close this issue if you are happy with the current implementation
