### ISSUE TITLE
GUI: user-defined distribution for stay duration

### ISSUE THREAD

**Issue by erees** [thibautjombart/covid19_bed_occupancy#9]
Need to add an optione to allow for user-defined distribution of duration of stay.
 - Need to decide what distribution we provide
- Need to decide what kind of input that is

**Comment by samclifford** [comment]
Are you thinking of using a drop-down menu to choose between Weibull and Gamma? Any others? And then you specify the two parameters?

**Comment by thibautjombart** [comment]
I'd like to leave this until after the first release. I realised this issue is not explicitely put in in project 2, fixing now.
